name: Main
on:
  push:
    branches:
      - main
  workflow_dispatch: { }
permissions:
  id-token: write # required for hashicorp/vault-action
  contents: read  # required for actions/checkout
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  Execute:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_TAG: "dev-${{ github.sha }}"
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: "https://mss.maersk.io/"
          method: jwt
          path: github-jwt
          role: "siriuslitedevdocs--maersk_global--siriuslitedevdocs"
          secrets: |
            siriuslitedevdocs-nonprod-kv/data/platform--harbor/siriuslitedevdocs server | CONTAINER_REGISTRY_SERVER;
            siriuslitedevdocs-nonprod-kv/data/platform--harbor/siriuslitedevdocs username | CONTAINER_REGISTRY_USERNAME;
            siriuslitedevdocs-nonprod-kv/data/platform--harbor/siriuslitedevdocs password | CONTAINER_REGISTRY_PASSWORD;
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY_SERVER }}
          username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ env.CONTAINER_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: amd64
          tags: "${{ env.CONTAINER_REGISTRY_SERVER }}/siriuslitedevdocs/siriuslitedevdocs:${{ env.DOCKER_IMAGE_TAG }}"
          labels: "org.opencontainers.image.revision=${{ github.sha }}"
          push: true
          sbom: true
          provenance: true
      - name: Output Docker Image Tag
        run: |
          echo "Docker image has been pushed with tag:"
          echo "  ${{ env.DOCKER_IMAGE_TAG }}"
